package utils.exceptions

case object UserPresentException extends Exception("User already present")